services:
  app:
    build:
      context: ./docker/backend/app
    container_name: loopitems_app
    restart: unless-stopped
    expose:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/
      - ./docker/backend/app/configs/.bashrc:/root/.bashrc
      - ./docker/backend/app/configs/.bashrc:/home/loopitems/.bashrc
      - ./docker/backend/app/configs/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/backend/app/configs/php.ini:/usr/local/etc/php/php.ini
      - ./docker/backend/app/configs/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/backend/app/configs/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/backend/app/extensions/Xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - loopitems_ntw

  web:
    build:
      context: ./docker/backend/web
    container_name: loopitems_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/backend/web/configs/.bashrc:/root/.bashrc
      - ./docker/backend/web/configs/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/backend/web/virtualHost/loopitems.conf:/etc/nginx/sites-enabled/loopitems.conf
    depends_on:
      - app
    networks:
      - loopitems_ntw

  bd_mysql:
    build:
      context: ./docker/db/mysql
    container_name: loopitems_bd_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/mysql/config/my.cnf:/etc/my.cnf
      - ./docker/db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "loopitems"
      MYSQL_USER: "loopitems"
      MYSQL_PASSWORD: "loopitems"
    networks:
      - loopitems_ntw

  cache_redis:
    build:
      context: ./docker/cache/redis
    container_name: loopitems_cache_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: loopitems
      REDIS_PORT: 6379
      REDIS_HOST: 127.0.0.1
      REDIS_DATABASES: 16
    volumes:
      - ./docker/cache/redis/data:/data
    networks:
      - loopitems_ntw

  node:
    build:
      context: ./docker/frontend/node
    container_name: loopitems_node
    restart: unless-stopped
    expose:
      - 3000
    ports:
      -  "3000:3000"
    volumes:
      - ./docker/frontend/node/app:/app
    networks:
      - loopitems_ntw

networks:
  loopitems_ntw:
    driver: bridge